server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:system/oracle@localhost:1521:xe}
    db-connection-timeout-seconds: ${DB_CONNECTION_TIMEOUT_SEC:180}
    initial_pool_size: ${INITIAL_POOL_SIZE:20}
    maxIdle: ${MAX_IDLE:50}
    maxActive: ${MAX_ACTIVE:100}