server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:system/oracle@localhost:1521:xe}
    db-connection-timeout-seconds: ${DB_CONNECTION_TIMEOUT_SEC:180}
    schemaname: ${SCHEMA_NAME:SYS}
    initial_pool_size: ${INITIAL_POOL_SIZE:20}
    maxIdle: ${MAX_IDLE:50}
    maxActive: ${MAX_ACTIVE:100}

liquibase-db:
  url: ${DB_URL:jdbc:oracle:thin:system/oracle@localhost:1521:xe}
  timeout_in_seconds: ${LIQUIBASE_DB_CONNECTION_TIMEOUT_SEC:180}
  connection_max_attempts: ${LIQUIBASE_DB_CONNECTION_MAX_ATTEMPTS:10}
  connection_retry_interval_in_millis: ${LIQUIBASE_DB_CONNECTION_RETRY_INTERVAL_MILLIS:1000}
  initial_pool_size: ${LIQUIBASE_DB_INITIAL_POOL_SIZE:2}
  maxIdle: ${LIQUIBASE_DB_MAX_IDLE:2}
  maxActive: ${LIQUIBASE_DB_MAX_POOL_SIZE:2}

logging:
  app:
    level: ${APP_LOG_LEVEL:INFO}